### ISSUE TITLE
希望uuidStyle的时间戳支持自定义

### ISSUE THREAD

**Issue by PandaNocturne** [calmwaves111/obsidian-uuid-plugin#2]
目前只提供这种YYYYMMDD_mmhhss选项，但我更想自定义的形式，比如：YYYYMMDDmmhhSSS，[Obsidian]-YYYYMMDDmmhhSSS

**Comment by calmwaves111** [comment]
https://github.com/calmwaves111/obsidian-uuid-plugin/releases/tag/0.0.9 已更新
